### ISSUE TITLE
"Integral" doesn't mean what you think it does.

### ISSUE THREAD

**Issue by anonymousAwesome** [spacetelescope/understanding-json-schema#33]
The following line is in numeric.rst:

> The integer type is used for integral numbers.

While that *sounds* good, there isn't really any such thing as an integral number.  When applied to numbers, the term "integral" generally refers to the area under the curve of a graphed function.  

To be correct (although redundant), the line should read, "The integer type is used for integers".

EDIT: Wait, never mind.  Definition 5 of integral from dictionary.reference.com:  

> Arithmetic. pertaining to or being an integer; not fractional.

**Comment by mdboom** [comment]
Still, if it's a source of confusion for other readers (even if strictly correct), I'm happy to change.

@embray: Any opinions?

**Comment by embray** [comment]
There's nothing wrong with "integral numbers"--I guess maybe that was chosen just to avoid writing "integer" twice in the same sentence.  Of course, it's an unfortunate sentence to even have to write since most people reading it will know what you mean by "integer type".  Maybe clarify:

> The integer type is used for strictly integer numbers.
