### ISSUE TITLE
Complex schema section

### ISSUE THREAD

**Issue by simon-p-r** [spacetelescope/understanding-json-schema#34]
This stackoverflow discussion highlights the failings of allOf

http://stackoverflow.com/questions/22689900/json-schema-allof-with-additionalproperties

I think there should be some reference to this as this could be miss leading to someone who hasn't encountered this problem.

**Comment by embray** [comment]
Ah, this is tricky, and new to me too--I hadn't encountered this problem.  Good to know, and definitely worth adding to the docs.
