### ISSUE TITLE
Properties as Property not working

### ISSUE THREAD

**Issue by Zilev** [spacetelescope/understanding-json-schema#47]
Hi, I would like to something like this:
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "properties": {
      "type": "object",
      "enum": "metadata"
    },
    "required": {
      "type": "array",
      "items": {
        "metadata": "string"
      }
    }
  }
}
```
but this part is not working well:
```
"properties": {
      "type": "object",
      "enum": "metadata"
 },
```
Is possible to do this? or is estrictamente prohibido to use those built schema words like: "required", "enum", "properties" as a property inside "properties"?.
Thanks in advance for helping me to understand this part :smile:

**Comment by Zilev** [comment]
I see, sorry, my mistake, I've created wrong the json schema, updating my json schema I dont have problems with properties as properties any more :)
```
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "id": "http://jsonschema.net",
  "type": "object",
  "properties": {
    "title": {
      "type": "string"
    },
    "type": {
      "type": "string"
    },
    "properties": {
      "type": "object",
      "properties": {
        "myData": {
          "type": "object"
        }
      }
    },
    "required": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  }
}
```
Is working fine :)

**Comment by embray** [comment]
Right--when interpreting a schema the keys in the "properties" property of a schema can be anything, even if they are terms like "properties" that have meaning elsewhere in a schema.
