### ISSUE TITLE
Enforce HTTPS

### ISSUE THREAD

**Issue by konklone** [spacetelescope/understanding-json-schema#53]
GitHub now lets you enforce HTTPS for `*.github.io` domains:

https://github.com/blog/2186-https-for-github-pages

The site already works over HTTPS: https://spacetelescope.github.io/understanding-json-schema/index.html There's a font URL that needs to be updated to `https://`, but that is a trivial fix.

![support page](https://help.github.com/assets/images/help/pages/enforce-https-checkbox.png)

**Comment by embray** [comment]
Done; thanks for pointing it out.

**Comment by konklone** [comment]
Awesome, thank you! :smiley_cat:
