### ISSUE TITLE
Simple Next Page Button

### ISSUE THREAD

**Issue by codeHatcher** [spacetelescope/understanding-json-schema#54]
I loved this quick tutorial. I would add a way to let me go from one page to the next without having to go back to the main menu. That small change would make a huge difference

**Comment by SaraOgaz** [comment]
Hi @codeHatcher, if I understand your question correctly, there are navigation buttons at the very top of the doc pages, the text is the title of the next section.  Is this what you were looking for?

**Comment by codeHatcher** [comment]
yup that’s it, on my monitor it’s super squished together so I didn’t realize that’s what that was for. Thanks!
