### ISSUE TITLE
header navigation error

### ISSUE THREAD

**Issue by fidelisrafael** [spacetelescope/understanding-json-schema#56]
Hi there!

I'm reading the online book(thanks you guys for this!), and found a small bug in [Generic Keywords page](https://spacetelescope.github.io/understanding-json-schema/reference/generic.html).
Navigation menu shows `null` as prev page, maybe this is an error in `sphynx`? I dont have any experience with `sphynx-doc`, so im still taking a look to see if I can fix this...
Maybe someone with more knowledgement in this subject can help fixing this (must be a easy task, I think).

ref image:

![](http://i.imgur.com/dA0fpXv.png)

**Comment by justincely** [comment]
hi @fidelisrafael,  the previous page is actually entitled "null" as that page specifically deals will null values in json schema.  You'll notice if you navigate backwards to [boolean](https://spacetelescope.github.io/understanding-json-schema/reference/boolean.html) the null page will have moved to the "next" item on the navigation bar.

**Comment by fidelisrafael** [comment]
@justincely You're right! I thought that was an reference error ;)
Thanks for replying.
